config/routes.rb
Sam::Application.routes.draw do
  get "login" => "admin#login"
  get "logout" => "admin#logout"

  get "home"  => "home#index"
  get "about" => "about#index"

  get "pubkey"=> "about#pubkey"
  get "keybase.txt" => "static#keybase"

  root :to => "home#index"

  resources :posts

  resources :projects do
    resources :posts
  end

  resources :images

end

app/models/image.rb
class Image < ActiveRecord::Base
  attr_accessible :description, :file
  has_attached_file :file, :styles => { :normal => "300x300", :thumb => "210x210", :small_thumb => "100x100" }

  validates :file, :attachment_presence => true
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :content, :title, :visible

  belongs_to :project

  def self.visible
    Post.where(:visible => true)
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :description, :title, :short_desc, :preview, :state, :visible
  has_attached_file :preview

  has_many :posts

  def self.all_states
    ["abandoned", "active", "finished"]
  end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end

  def pubkey
    send_file "app/assets/data/pubkey.asc"
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

  def login
    if authenticate_with_http_basic { | user, password | user == ADMIN_CREDENTIALS["username"] && password == ADMIN_CREDENTIALS["password"] }
      start_session
    else
      request_http_basic_authentication
    end
  end

  def logout
    end_session
    redirect_to :controller => "home"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :authenticated?
  helper_method :start_session
  helper_method :end_session

  def raise_404
    raise ActionController::RoutingError.new('Not Found')
  end

protected
  def authenticated?
    session[:authorized]
  end

  def start_session
    session[:authorized] = true
  end

  def end_session
    session[:authorized] = false
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if authenticated?
      @posts = Post.order("created_at DESC")
    else
      @posts = Post.where(:visible => true).order("created_at DESC")
    end
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_filter :authenticated?, :except => [:show]

  def index
    @images = Image.all
  end

  def show
    @image = Image.find(params[:id])
    render :layout => false
  end

  def new
    @image = Image.new
  end

  def create
    @image = Image.new(params[:image])

    if @image.save
      redirect_to :action => :index
    else
      render :action => new
    end
  end

  def edit
    @image = Image.find(params[:id])
    render :action => :new
  end

  def update
    @image = Image.find(params[:id])

    if @image.update_attributes(params[:image])
      redirect_to :action => :index
    else
      render :action => new
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticated?, :except => [:index, :show]

  def index
    if authenticated? then
      @posts = Post.where(:project_id => nil)
    else
      @posts = Post.where(:project_id => nil, :visible => true)
    end
  end

  def show
    @post = Post.find(params[:id])

    unless @post.visible or authenticated?
      raise_404
    end
  end

  def edit
    if params[:project_id]
      @project = Project.find(params[:project_id])
    else
      @project = false
    end

    @post = Post.find(params[:id])

    render :action => :new
  end

  def update
    @post = Post.find(params[:id])
    if params[:project_id]
      @project = Project.find(params[:project_id])
      if @post.update_attributes(params[:post])
        redirect_to @project
      else
        render :action => :new
      end
    else
      @project = false
      if @post.update_attributes(params[:post])
        redirect_to @post
      else
        render :action => :new
      end
    end
  end

  def new
    if params[:project_id]
      @project = Project.find(params[:project_id])
      @post = @project.posts.build
    else
      @project = false
      @post = Post.new
    end
  end

  def create
    if params[:project_id]
      @project = Project.find(params[:project_id])
      @post = @project.posts.create(params[:post])
      redirect_to project_path(@project)
    else
      @post = Post.create(params[:post])
      redirect_to @post
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :authenticated?, :except => [:index, :show]

  def index
    if authenticated?
      @projects = Project.all
    else
      @projects = Project.where(:visible => true)
    end
  end

  def show
    @project = Project.find(params[:id])
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(params[:project])

    if @project.save
      redirect_to @project
    else
      render :action => :new
    end
  end

  def edit
    @project = Project.find(params[:id])
    render :action => :new
  end

  def update
    @project = Project.find(params[:id])

    if @project.update_attributes(params[:project])
      redirect_to @project
    else
      render :action => :new
    end
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def keybase
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  class String
    def is_integer?
      self.to_i.to_s == self
    end
  end

  def markdown(text)
    # parse image tags [img:123] --> ![description](url)
    # or [thumb:123]
    text.gsub!(/\[(img|thumb|project|post)(:L|:R)?:(\d+)\]/) do |match|
      if $1 == "img" || $1 == "thumb"
        img = Image.find($3.to_i)
        c = "post_image"
        if $2 == ":L"
          c = "post_image_left"
        elsif $2 == ":R"
          c = "post_image_right"
        end
        link_to( \
          image_tag(img.file.url(if $1 == "img" then :normal else :thumb end), class: c, alt: img.description), \
          image_url(img))
      elsif $1 == "project"
        proj = Project.find($3.to_i)
        "[#{proj.title}](#{project_url(proj)})"
      elsif $1 == "post"
        post = Post.find($3.to_i)
        "[#{post.title}](#{project_post_url(post.project, post)})"
      else
        "ERROR"
      end
    end

    markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, :autolink => true, :space_after_headers => true, :fenced_code_bocks => true)
    markdown.render(text).html_safe
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/about/index.html.erb
<div id="content_left">
  <%= image_tag "id.jpg" %>
</div>

<div id="content">
  <h2>SAMUEL BRYNER</h2>

  I'm a student of Computer Science at ETH Zürich, were I'm killing my time coding and soldering a lot of things.
  Some of them are or will be presented on this site.
  <br>
  <br>
  Otherwise, I love flying trough the skies and I am secretly working on taking over the world.
  <br>
  <br>
  You'll find me in various places on the internet:<br>
  <a href="mailto:samuelbryner@gmx.ch">samuelbryner@gmx.ch</a><br>
  <a href="https://github.com/iliis">GitHub</a><br>
  <a href="https://iliis.deviantart.com/">DeviantArt</a><br>
  <a href="https://plus.google.com/u/0/100342361785767319338/">Google+</a><br>
  <a href="https://keybase.io/iliis">Keybase</a>
  <br>
  <br>
  Curriculum vitae available on request.
  <br>
  <br>
My public key: <%= link_to "0x4CBB15F4", "pubkey" %><br>
Fingerprint: <code>FDE2 A5F8 DEF3 8648 5A75  66FB F8F1 81F9 4CBB 15F4</code>
</div>

app/views/admin/login.html.erb
<h2>Successfully Authenticated</h2>
You should be able to edit this site now.

app/views/home/index.html.erb
<div id="content_left">
  <%= image_tag "drawing.jpg" %>
</div>

<div id="content">
  <h2>NEWS</h2>

  Hi.<br>
  Now where is my GeoCities Work In Progress Coming Soon&trade; picture?<br>
  This site will host some projects I made in the hope of inspiring others and to show off my awesomeness!
  <br>
  <br>
  Please note that this site is still early work in progress. There is not much content and some things may not work properly.
  If you find such things do not hesitate to <%= link_to "contact me", :controller=>:about %>!
  <br>
  <br>

  <%= render @posts, show_project_tag: true %>
</div>

app/views/images/index.html.erb
<h2>IMAGES</h2>
<%= link_to "upload image", new_image_path() %><hr>

<% @images.each do |image| %>
	<div class="small_img">
		<%= link_to(image_tag(image.file.url(:small_thumb)), edit_image_path(image)) %>
	</div>
<% end %>

app/views/images/new.html.erb
<h2>new/edit image</h2>

<%= image_tag @image.file.url(:normal) if @image.file.present? %>

<%= form_for(@image) do |f| %>
	<%= f.file_field :file %>
	<br>
	<%= f.text_area :description%>
	<br>
	<%= f.submit %>
<% end %>

app/views/images/show.html.erb
<%= image_tag @image.file.url, alt: @image.description %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>sam's site</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="sam">
    <title>Sam</title>

    <link href='http://fonts.googleapis.com/css?family=Pathway+Gothic+One' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Amethysta' rel='stylesheet' type='text/css'>
    <!--<link href='http://fonts.googleapis.com/css?family=Cinzel:400,700' rel='stylesheet' type='text/css'>-->
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
	  <div id="main">
		  <div id="header">
			  <% if authenticated? %>
				  <%= link_to "logout", :controller=>:admin, :action=>:logout %>
				  <h1>Hallo Sam</h1>
			  <% else %>
				  <h1>Hallo Welt</h1>
			  <% end %>
			  <hr>
			  <%= render 'shared/main_menu' %>
			  <hr>
		  </div>

		  <%= yield %>
	  </div>
  </body>
</html>

app/views/posts/_post.html.erb
<div class="post">
<% if post.project %>
  <% if defined?(show_project_tag) %>
      <h3><a href="<%= project_url(post.project) %>" >[<%= post.project.title %>] <%= post.title %></a></h3>
  <% else %>
      <h3><%= post.title %></h3>
  <% end %>
<% else %>
  <% if defined?(show_project_tag) %>
	<h2><%= link_to post.title, post %></h2>
  <% else %>
	<h2><%= post.title %></h2>
  <% end %>
<% end %>

<small>posted at: <i><%= post.created_at %></i>
	<% if post.created_at != post.updated_at %>
		- last update: <i><%= post.updated_at %></i>
	<% end %>

    <% if authenticated? %>
      <% if post.project %>
        <%= link_to "edit", edit_project_post_path(post.project, post) %>
      <% else %>
        <%= link_to "edit", edit_post_path(post) %>
      <% end %>
    <% end %>

    <% if ! post.visible? %><b>hidden</b><% end %>
</small>

<%= markdown(post.content) %>
</div>

app/views/posts/index.html.erb
<h2>TEXT</h2>
<% if authenticated? %>
  <%= link_to "add post", new_post_path() %>
  <br>
  <a href="https://de.wikipedia.org/wiki/Markdown">Markdown Syntax</a> provided by <a href="https://github.com/vmg/redcarpet">Redcarpet</a>
<% end %>
Random notes, interesting tibits, toughts, ideas, etc.
<hr>

<ul>
<% for p in @posts %>
  <li>
  <h3>
    <%= link_to p.title, p %>
    <% unless p.visible %>
      [hidden]
    <% end %>
  </h3>
  </li>
<% end %>
</ul>

app/views/posts/new.html.erb
<% if @project %>
  <h2>post for project '<%= @project.title %>'</h2>

  <%= form_for([@project, @post]) do |f| %>
      <%= f.label :title, "Title:" %>
      <%= f.text_field :title %>
      <br>
      <%= f.check_box :visible %>
      <%= f.label :visible, "visible to public" %>
      <br>
      <%= f.text_area :content %>
      <br>
      <%= f.submit %>
  <% end %>
<% else %>
  <h2>general post without project</h2>

  <%= form_for(@post) do |f| %>
      <%= f.label :title, "Title:" %>
      <%= f.text_field :title %>
      <br>
      <%= f.check_box :visible %>
      <%= f.label :visible, "visible to public" %>
      <br>
      <%= f.text_area :content %>
      <br>
      <%= f.submit %>
  <% end %>
<% end %>

app/views/posts/show.html.erb
<%= render @post %>

app/views/projects/_project_preview.html.erb
<div class="project_preview">

  <% if proj.preview? %>
    <%= link_to(image_tag(proj.preview.url), project_path(proj)) %>
  <% else %>
    <div style="background-color: #555; width: 210px; height: 210px; margin: 0px;">image missing</div>
  <% end %>

  <div class="project_preview_text">
    <h3><%= link_to proj.title, project_path(proj) %></h3>

    <% if authenticated? %>
      <%= link_to "edit", edit_project_path(proj) %>
      <% if ! proj.visible? %><b>hidden</b><% end %>
    <% end %>

    <%= markdown(proj.short_desc) %>
  </div>
</div>

app/views/projects/index.html.erb
<!--<div id="content_left">
  <%= image_tag "mkbot.jpg" %>
</div>

<div id="content">-->
  <h2>PROJECTS</h2>
  <% if authenticated? %>
	  <%= link_to "create new project", new_project_path %><br>
  <% end %>

  <%= render :partial => "project_preview", :collection => @projects, :as => "proj" %>
  <!--</div>-->

app/views/projects/new.html.erb
<h2>new/edit project</h2>

<%= form_for @project do |f| %>
	<%= f.label :title, "title:" %>
    <%= f.text_field :title %>
    <br>

    <%= f.label :state, "state: "%>
    <%= f.select :state, options_for_select(Project.all_states, @project.state) %>
    <br>

    <%= f.check_box :visible %>
    <%= f.label :visible, "visible to public" %>
    <br>

    <%= f.label :preview, "preview image (210x210px):" %>
    <%= f.file_field :preview %>
    <br>

    <%= f.label :short_desc, "short description:" %><br>
    <%= f.text_area :short_desc, :style => "height: 100px;" %>
    <br>

	<%= f.text_area :description %>
	<br>

	<%= f.submit "save" %>
<% end %>

app/views/projects/show.html.erb
<div class="project">
  <h2><%= @project.title %></h2>
  <small>state: <i><%= @project.state %></i></small><br>
  <%= (link_to "edit", edit_project_path(@project)) + " /" if authenticated? %>
  <%= link_to "add post", new_project_post_path(@project) if authenticated? %>

  <%= markdown(@project.description) %>

  <%= render @project.posts.order("created_at ASC") %>
</div>

app/views/shared/_main_menu.html.erb
<% entries = {"news" => "home", "projects" => "projects", "text" => "posts", "about me" => "about"} %>

<% entries["images"] = "images" if authenticated? %>

//
<% entries.each do |text, dest| %>
  <% if current_page?(url_for(:controller => dest)) %>
    <b><%= text.upcase %></b>
  <% else %>
    <%= link_to text.upcase, url_for(:controller => dest) %>
  <% end %>
  //
<% end %>